import Head from 'next/head'
import { NavLink } from '../app/components/NavLink';
import Image from 'next/image'
import Card from '../app/components/Card';
import Button from '../app/components/Button';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="container my-6 mx-auto  border-y border-white">
        <nav className="w-100">
          <ul className="flex flex-row p-0 m-0">
            <li className="flex-initial w-3/6">
              <NavLink href="/" className="p-3 inline-block">GEOMAN AI</NavLink>
            </li>
            <li className="flex-initial w-2/6">
              <NavLink href="/" className="p-3 inline-block">SOLUTIONS</NavLink>
            </li>
            <li className="flex-initial w-1/6 text-right">
              <NavLink href="/" className="p-3 inline-block">PROJECTS</NavLink>
            </li>
          </ul>
        </nav>
      </header>

      <main className="container mx-auto">
        <div className="flex flex-row items-start">
          <h1 className="text-4xl flex-initial w-3/6">
            REAL-TIME<br />
            MANAGEMENT<br />
            AND ANALYSIS
          </h1>

          <h3 className="text-xl flex-initial w-2/6">
            HIGH <br/>
            QUALITY
          </h3>

          <div className="flex-initial w-1/6 text-right">
            <Button href="/">Get stared</Button>
          </div>
          
        </div>

        <div className="flex sm:flex-col md:flex-row gap-12 items-start mt-5">
          <div className="flex-initial sm:w-full md:w-2/3">
            <Card headPosition='left' color='green'>
              <div className={styles.card}>
                <div className="relative top-8 flex items-center justify-center">
                  <Image src="/images/man.png" width="500" height="700" objectFit='contain' />
                </div>
                <p className="absolute bottom-10 left-10 text-black text-xl font-medium">
                  Because your<br />
                  business needs<br />
                  a lot more
                </p>
                <Button href="/" className="bg-transparent absolute bottom-10 right-10">Get expert advise</Button>
              </div>
            </Card>
          </div>
          <div className="flex-initial sm:w-full md:w-1/3">
            <Card headPosition='left' color='gold'>
              <div className={styles.card}>
                <h4 className="text-3xl text-black text-center font-medium"><span className="font-light">The</span> <br/> Future</h4>  
                <div className="flex flex-col items-center justify-center">
                  <Image src="/images/man.png" width="500" height="700" className="h-full" objectFit='contain' />
                  <p className="absolute bottom-10 w-40 text-xl text-black text-center font-medium">
                    Free your mind for something <strong>more important</strong>
                  </p>
                </div>
              </div>
            </Card>
          </div>
        </div>
      </main>
    </div>
  )
}
